services:
  minecraft-server:
    build:
      context: .
      args:
        FORGE_VERSION: ${FORGE_VERSION}
        MEMORY_ALLOCATION: ${MEMORY_ALLOCATION}
    image: minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ${MINECRAFT_HOST_DIR}:/minecraft/world/
    networks:
      - minecraft_network
    stdin_open: true
    tty: true

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: unless-stopped
    command:
      - "tcp"
      - "minecraft-server:25565"
      - "--log=stdout"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - minecraft_network

networks:
  minecraft_network:
    driver: bridge
